const actionTypes = {
  SET_SHARED_EDITOR_VALUE: "SET_SHARED_EDITOR_VALUE",
  SET_SHARED_EDITOR_REMOTE_CHANGE: "SET_SHARED_EDITOR_REMOTE_CHANGE",
  SET_SHARED_EDITOR: "SET_SHARED_EDITOR",
  SET_CHAT: "SET_CHAT",
  SET_PROJECTS: "SET_PROJECTS",
};

export default actionTypes;
