const actionTypes = {
  SET_SHARED_EDITOR_VALUE: "SET_SHARED_EDITOR_VALUE",
  SET_CHAT: "SET_CHAT",
  SET_PROJECTS: "SET_PROJECTS",
  ADD_PROJECT: "ADD_PROJECT",
  REMOVE_PROJECT: "REMOVE_PROJECT",
  SET_CURRENT_PROJECT_ID: "SET_CURRENT_PROJECT_ID",
  ACCEPT_PROJECT: "ACCEPT_PROJECT",
  SET_USER_NAME: "SET_USER_NAME",
};

export default actionTypes;
