const actionTypes = {
  SET_SHARED_EDITOR_VALUE: "SET_SHARED_EDITOR_VALUE",
  SET_CHAT: "SET_CHAT",
  SET_PROJECTS: "SET_PROJECTS",
  ADD_PROJECT: "ADD_PROJECT",
  REMOVE_PROJECT: "REMOVE_PROJECT",
};

export default actionTypes;
